### ISSUE TITLE
error install with docker 

### ISSUE THREAD

**Issue by fturiot** [kirill-zhirnov/boundless-commerce-os-admin#1]
hello,

after docker exec -it ecommerce-admin-1 ./shell.ts selfHosted install

i have error : 
aftter enter email 
DatabaseError [SequelizeDatabaseError]: relation "vw_city" does not exist
    at Query.formatError (/home/node/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/node/app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at tryCatcher (/home/node/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/node/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/node/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/node/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/node/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/node/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/node/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/node/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:476:21) {
  parent: error: relation "vw_city" does not exist
      at Parser.parseErrorMessage (/home/node/app/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (/home/node/app/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (/home/node/app/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (/home/node/app/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (node:events:517:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Socket.Readable.push (node:internal/streams/readable:278:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 105,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'namespace.c',
    line: '432',
    routine: 'RangeVarGetRelidExtended',
    sql: 'REFRESH MATERIALIZED VIEW vw_city',
    parameters: undefined
  },
how solve this 
thanks for all

**Comment by kirill-zhirnov** [comment]
Hi @fturiot 
Thanks for the report!

How did you setup DB? Manually or via our docker img?

**Comment by fturiot** [comment]
hi @kirill-zhirnov 
with docker with compose
regards

**Comment by kirill-zhirnov** [comment]
Did you put `.env` file near the `docker-compose.yaml`? What is in the .env?

**Comment by fturiot** [comment]
yes .env
 GNU nano 6.2                                                                                                        .env                                                                                                                  
"COMPOSE_PROJECT_NAME=ecommerce

NODE_ENV=production

POSTGRES_PASSWORD=123
DB_HOST=db

RABBIT_MQ_HOST=rabbitmq
RABBIT_MQ_USER=guest
RABBIT_MQ_PASS=guest

REDIS_URL=redis://redis

MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
MEMCACHED_DSN=memcached:11211

# If you need file uploader - uncomment and put the appropriate values:
#S3_KEY=your S3 Key
#S3_SECRET=your S3 Secret
#S3_BUCKET=S3 Bucket name
#S3_ENDPOINT=S3 endpoint, e.g. nyc3.digitaloceanspaces.com
#S3_REGION=S3 region, e.g. nyc3

# Image resizer address
S3_MEDIA_SERVER=http://localhost:3002

# If you need email notifications - uncomment and put credentials for the AWS SES:
#AWS_SES_KEY=key
#AWS_SES_SECRET=secret
#AWS_SES_REGION=region"

**Comment by fturiot** [comment]
hi @kirill-zhirnov 
it's solve but without change , i do not understand
who can i create other shop with other user ?
thanks for all

**Comment by kirill-zhirnov** [comment]
@fturiot and what is it `GNU nano 6.2 .env` ?) Can you please post a content of the file wrapped in ``` ?

**Comment by fturiot** [comment]
@kirill-zhirnov it's only after GNU nano 6.2 .env
it's paste from linux term and nano editor

**Comment by kirill-zhirnov** [comment]
To create another shop you can do: `docker exec -it ecommerce-admin-1 ./shell.ts instance start --client=1 --email=<email>`

And then switch shop by specifeing `INSTANCE_ID` in the env. If you want to work multiple instance simunteniously - it is out of our open source solution, but can be easily setup with NGNIx and minor patch :)

**Comment by fturiot** [comment]
thanks for all
